### ISSUE TITLE
Env variables should be parsed regardless of whether safeCheck is truthy

### ISSUE THREAD

**Issue by genu** [rubiin/nestjs-easyconfig#142]
https://github.com/rubiin/nestjs-easyconfig/blob/f8e9e707dcfb2d27dd7b9e56bebbb8aee099d6b8/src/easyconfig.service.ts#L78

It is my understanding that the `safeCheck` is just to make sure that all the needed env keys are defined, not whether they contain any specific value.

The parsing of variables should happen in all cases, right?

In the current behavior, `safe: false` is required for the env to be parsed using `dotenv-parse-variables`

**Comment by genu** [comment]
If this is a bug, I can PR a fix real quick.

**Comment by rubiin** [comment]
please do.

**Comment by rubiin** [comment]
On second thought, we may have to let users decide on this so I am leaving this open until a consensus is met

**Comment by genu** [comment]
Hmm... what’s the implication? 

The tests are failing at the moment I believe. 

At the very least, the tests should be updated to reflect the expected behavior.

**Comment by rubiin** [comment]
Just ran the tests,which failed at the safe: true condition, lets get this patched then

**Comment by rubiin** [comment]
@genu i have asked for some changes in the pr, and we should be good to go
