### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by rubiin** [rubiin/nestjs-easyconfig#57]
Add new features in documentation

**Comment by bradtaniguchi** [comment]
One of the features missing from the documentation is the addition of the [dotenv-parse-variables ](https://www.npmjs.com/package/dotenv-parse-variables) package that was added in this commit: 2cafd955e9299bf9b620f7192810bb43fbc02332

**Comment by rubiin** [comment]
cool. will look it

**Comment by dlukanin** [comment]
Hey. I'll add some docs about parsing variables in env file in a couple of days.

**Comment by rubiin** [comment]
Help yourself. I will assign the issue to you then
